# Generated by Django 3.2.12 on 2023-06-09 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Automovil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(blank=True, max_length=10)),
                ('marca', models.CharField(blank=True, max_length=15)),
                ('modelo', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='EspacioEstacionamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Tarifa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=20)),
                ('apellido', models.CharField(blank=True, max_length=25)),
                ('cedula', models.CharField(blank=True, max_length=10)),
                ('direccion', models.CharField(blank=True, max_length=50)),
                ('auto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.automovil')),
            ],
        ),
        migrations.AddField(
            model_name='automovil',
            name='espacio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.espacioestacionamiento'),
        ),
    ]
