# Generated by Django 3.2.12 on 2023-06-09 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_cliente_auto'),
    ]

    operations = [
        migrations.AddField(
            model_name='espacioestacionamiento',
            name='codigoIdentificativo',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='espacioestacionamiento',
            name='estadoEstacionamiento',
            field=models.BooleanField(default=True),
        ),
    ]
