# Generated by Django 3.2.12 on 2023-06-09 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20230609_0324'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarifa',
            name='descripcionTarifa',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AddField(
            model_name='tarifa',
            name='nombreTarifa',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='tarifa',
            name='precioTarifa',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
    ]
