# Generated by Django 3.2.12 on 2023-06-09 03:48

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20230609_0326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='automovil',
            name='espacio',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='auto',
        ),
        migrations.CreateModel(
            name='AutoEspacio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horaIngreso', models.DateField(blank=True, verbose_name=datetime.datetime(2023, 6, 9, 3, 48, 16, 771515))),
                ('auto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.automovil')),
                ('espacio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.espacioestacionamiento')),
                ('tarifa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.tarifa')),
            ],
        ),
    ]
