# Generated by Django 3.2.12 on 2023-06-09 03:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20230609_0348'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='auto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.automovil'),
        ),
        migrations.AlterField(
            model_name='autoespacio',
            name='horaIngreso',
            field=models.DateField(blank=True, verbose_name=datetime.datetime(2023, 6, 9, 3, 54, 3, 764731)),
        ),
    ]
