# Generated by Django 4.2.2 on 2023-07-03 21:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_autoespacio_horaingreso'),
    ]

    operations = [
        migrations.CreateModel(
            name='Egreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(blank=True, decimal_places=2, max_digits=4)),
                ('descripcion', models.CharField(max_length=450)),
                ('fechaCreacion', models.DateField(verbose_name=datetime.datetime(2023, 7, 3, 21, 44, 9, 920557))),
            ],
        ),
        migrations.CreateModel(
            name='Ingreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(blank=True, decimal_places=2, max_digits=4)),
                ('descripcion', models.CharField(max_length=450)),
                ('fechaCreacion', models.DateField(verbose_name=datetime.datetime(2023, 7, 3, 21, 44, 9, 920413))),
            ],
        ),
        migrations.AlterField(
            model_name='autoespacio',
            name='horaIngreso',
            field=models.DateField(blank=True, null=True, verbose_name=datetime.datetime(2023, 7, 3, 21, 44, 9, 920214)),
        ),
    ]
